[build]
  command = "npm run build"
  functions = "frontend/functions"
  publish = "frontend/dist"

[dev]
  command = "npm run dev --prefix frontend"
  port = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
