services:
  - type: web
    name: officecalendar-backend
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://postgres.asgaklfqlgzqriwdihyd:MzZTaRK0OwXWlnvK@aws-1-eu-central-1.pooler.supabase.com:5432/postgres
